language: python
python:
- '2.7'
install: pip install -r requirements.txt
before_script: python -c "import sys; print sys.path"
script: nosetests --with-coverage
after_success:
- codeclimate-test-reporter
env:
  global:
    secure: tMHlNQ0+5pbvjvPEmSBh+QrD6dND5kyc20hyR0zR9dLvxHSOlVmlEhLT9E8WoO6CELKOUkVY86GJSS9UijeFmnx1F+QlgV9Q5dfwH+fxF5hBWpL30MAwvlt1jXskQQZZicvoUxbBJM39nbTx31geDdNRaLJrps1cVhs5Iyqhe8gcEh0OzAZLDSKXQaw7q0KUTLviV2RiysFd7ZJ9hQsGYnVzVxphjtiasj1LAKHussGdCBjkKztjJOdCaZxp2GwbPRnY8Q5+OcerYceNUkJE4ymtdDWOHegAOTjE2k9x5jKX45SOG/QotogJqUMsfEy5FuP5pq/+gYJ0fGSdVpZjeTzfVeDFAU/EQHC1kCoiwI9w5yKR/Wn5QvDj+RqUM6Xd+W14xBQoBk8TfzT5ZXi/lG7slDWyrMxmcc2okVQ8H1ekQ2vN02LJyjS9o/C+AGtAz7ioaxTeZ4Yww1Sq8w3BxvQ+BJB+lsMIZUPfKxpafyIe4zCuTuF/17XcpiZgsMlVrDWcGlDeUonTatyO8ghE2cAA43kpV4lcvyrBLdkKH9RmETjj/BFOhtozOnC8grdGPrPKNWI9Kdh0eVeR5Hrv87BYPTLxSZHByZiNpgjQqPc1pXc+n+Ea2n3z4TFSqFb2OM7Pq8gi1nBOjnWc+cRLbMg8pxHmIsT1dT3KFJslQ+M=
