runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /run
  script: main.app
  login: admin

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /.*
  script: main.app

libraries:
- name: ssl
  version: latest
